### ISSUE TITLE
Failed import items and triggers with the template

### ISSUE THREAD

**Issue by kohan2392** [southbridgeio/zabbix-review-export-import#2]
Hi,
I exported template from zabbix1 and imported to zabbix2.
The template was created but without items and triggers.

**Comment by evgkrsk** [comment]
Yep, there is such problem in current code.

PR are welcome.

**Comment by ivanmirandaf** [comment]
Olá, ao importar um host obtive o seguinte erro.

`2021-04-30 17:12:46,649 INFO     JSON-RPC Server Endpoint: http://localhost/zabbix/api_jsonrpc.php
2021-04-30 17:12:52,061 INFO     Trying to load Zabbix object (type: host) from: /home/zabbix-review/hosts/PAINEL-CYB-C.Q-5.8.yaml
2021-04-30 17:12:52,111 ERROR    KeyError('default',)
Traceback (most recent call last):
  File "zabbix-import.py", line 1518, in main
    host_cache,
  File "zabbix-import.py", line 406, in import_host
    for i in host["interfaces"]["interface"]
  File "zabbix-import.py", line 406, in <listcomp>
    for i in host["interfaces"]["interface"]
KeyError: 'default'
2021-04-30 17:12:52,113 ERROR    Operation failed
2021-04-30 17:12:52,113 ERROR    Some operations failed`

**Comment by gjaekel** [comment]
May you also add the failing yaml file, please? If possible, cut down to the problematic part.

**Comment by ivanmirandaf** [comment]
Desculpa, acabei descobrindo que o meu zabbix não aceita o formatado YAML. Esse escript eu consigo exportar no formato XML?

**Comment by evgkrsk** [comment]
Please don't mess up different issues. Open new issue and attach failing yaml file and full --debug output, plus zabbix, python3 and OS versions.
